### ISSUE TITLE
Systematize `nix build`, `nix shell`, `nix develop`, etc (tracking issue)

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#10504]
**Is your feature request related to a problem? Please describe.**

As discussed in the meeting of 2024-04-15, we propose a new, more systematic naming scheme for these commands, so that they fit into the noun-verb format.
Aliases for the current "short commands" will be kept. The purpose of the scheme is to make it so that by following the aliases, the other, less used functionality becomes more easily discoverable.

**Describe the solution**

Add plumbing commands, and turn the short commands such as `nix run` into aliases that point to the right place in this noun-verb command hierarchy:

- `nix dev`: behaviors that use a `nix develop`-like interpretation of installables, or (later) #7501
  - [ ] `nix dev print-env`: `nix print-dev-env`
  - [ ] `nix dev shell`: `nix develop`
  - [ ] `nix dev run`: `nix develop -c`
  - [ ] `nix dev script`: scoped out for now (could print a script suitable for `$SHELL`; depends on #7501)

- `nix env`: commands that modify the environment
  -   `nix env run`: setenv + execvp (not decided - maybe this should instead just be a flag to `nix run`/`nix package run`?)
  - [ ] `nix env shell`: `nix shell`, ie setenv + start `$SHELL`
  - [ ] `nix env print-env`: mirrors `nix dev print-env` - expected to be a simple command
 
 - `nix package`: "normal" use of installable (whatever that means for the verb)
      - [ ] `nix package build`: `nix build`
      - [ ] `nix package run`: `nix run`
      - [ ] `nix package info`: new command, behaving like `--dry-run --json`, but also prints `meta`
      - [ ] `nix package edit`: `nix edit`

- `nix sandbox`: issue tbd (@roberth)

**Describe alternatives you've considered**

There's a long thread, #4715, but note that it's mostly about one or two command; it rarely discusses a naming _system_.

**Additional context**

This is somewhat based on https://github.com/NixOS/nix/issues/4715#issuecomment-917069357, but with new insights and team discussion.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
Perhaps `nix profile run` could be added, to assemble a temporary profile and run a command with it.

Similarly `nix profile shell`. We'd have to decide whether those transient profiles are mutable. It seems feasible, and we could set something like a `NIX_PROFILE` environment variable (also used by `nix-env`; compatible??), so that nested `nix profile` mutation calls operate on that profile.

**Comment by BLANKatGITHUB** [comment]
Well , I would like to help in this issue, I am first time contributing here and would appreciate some help.

**Comment by roberth** [comment]
### No "idea approved" label yet

But that doesn't _have_ to be a problem and I did propose this in a meeting, so it's not entirely crazy.
I'm double checking with the team that this proposal is ok. I'm not 100% sure about the `package` subcommands. 

### Development setup

A good place to get started is the [page about development in the manual](https://nix.dev/manual/nix/development/development/index.html). This includes things like building it, and setting up `clangd`. We're switching to meson for building right around now, so feedback is extra appreciated. That's also why I'm linking URLs to the `development` version of the URL despite its odd redirect UX.
Make sure you set up a language server. A lot of the effort picking up a new project is reading and navigating, and an LSP helps a lot with the navigating. A lot of what I do is Ctrl+click or Ctrl+Enter to open things, and then I have a custom keybinding for navigating back. `git grep` or a "global find" feature do the other 30% of navigation.

### First change to pick

When you've run a local build, I think you could start with a rename like `nix env run`, which would be analogous to https://github.com/NixOS/nix/pull/10807.
The ones that don't say (rename+alias) tend to be more complicated, but I think we can treat `nix env run` as a (rename+alias) now.

> * `nix dev run`: `nix develop -c` ([rename+alias](https://github.com/NixOS/nix/issues/10507))

I would guess that this is not actually a rename and alias in terms of implementation; only UX-wise. This probably involve some refactoring so that we have two commands invoking the same piece of code.

If you're doing something that creates new behaviors that aren't simply aliases, also read up on testing. We do almost all of our CLI testing in `tests/functional`, but the manual will tell you [more](https://nix.dev/manual/nix/development/development/testing.html#functional-tests) about that.

More info about contributing is also [in the manual](https://nix.dev/manual/nix/development/development/contributing) and in [CONTRIBUTING.md](https://github.com/NixOS/nix/blob/master/CONTRIBUTING.md).

**Comment by BLANKatGITHUB** [comment]
So like should I wait till the idea is approved right? 
Meanwhile I can read all the docs and familiarise myself with the environment.
I appreciate your help though.

**Comment by BLANKatGITHUB** [comment]
Sorry ,I am kind of busy with my college exams and projects so didnt had much time recently but I would like to start if you okay with it , can you give me an general idea where to start and how.

**Comment by a-peirogon** [comment]
I'm interested in contributing to this issue. 

I noticed that:
- the issue was removed from the Nix team project on Nov 27
- there's no "idea approved" label yet

Could you clarify the current status? Which parts of the proposal are still valid and open for contribution?
