### ISSUE TITLE
Flake User's Documentation

### ISSUE THREAD

**Issue by MarekPasnikowski** [NixOS/nix#6079]
# A Simple Flake Documentation
I decided to open this issue to communicate questions someone like me will have when trying to use flakes. I know very little about programming and system administration. I am clever just enough to follow good instruction manuals. The problem begins, when the manuals are bad or don't exist at all. This is my attempt to direct creation of a manual which is readable by anyone.

# Task List
- [x] Obtain a good formatting tool.
- [ ] Introduce the flake structure.
    - [ ] 1. Collect information.
    - [ ] 2. Filter information.
    - [ ] 3. Compose remaining information.
- [ ] Document the description attribute.
    - [ ] 1. Collect information.
    - [ ] 2. Filter information.
    - [ ] 3. Compose remaining information.
- [ ] Document the inputs attribute.
    - [ ] 1. Collect information.
    - [ ] 2. Filter information.
    - [ ] 3. Compose remaining information.
- [ ] Document the outputs attribute.
    - [ ] 1. Collect information.
    - [ ] 2. Filter information.
    - [ ] 3. Compose remaining information.

**Comment by edolstra** [comment]
See also #5955.

**Comment by Obikawa** [comment]
Thank you.

 Will it be fine, if I open a ==draft== pull request to automatically present my progress?

**Comment by fricklerhandwerk** [comment]
@Obikawa if you're still interested or actively working on this, please check [ongoing efforts](https://github.com/orgs/NixOS/projects/15/) by the [Nix documentation team](https://discourse.nixos.org/t/documentation-team-flattening-the-learning-curve/20003). We'll gladly help you along with getting things merged.

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.
